on: [push]

jobs:
  create_installer:
    runs-on: windows-latest
    steps:      
    - name: Create nsis installer
      uses: joncloud/makensis-action@v2.0
      with:
        script-file: "TETools-create-exe.nsi"
